apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w4ylchvr8-go 
  janus-idp.io/tekton: w4ylchvr8-go
  backstage.io/kubernetes-id: w4ylchvr8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w4ylchvr8-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml